# Generated by Django 3.1.4 on 2020-12-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to='dishimg/%y-%m-%d'),
        ),
    ]
