# Generated by Django 3.1.4 on 2020-12-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0003_rest_dish_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to='templates/%y-%m-%d'),
        ),
    ]
